-- Base schema for Drizzie City Portal

CREATE TABLE IF NOT EXISTS Accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nickname VARCHAR(32) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  salt VARCHAR(64) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  discord_id VARCHAR(32) DEFAULT NULL,
  vip_until DATETIME NULL,
  money BIGINT DEFAULT 0,
  bank BIGINT DEFAULT 0,
  cash BIGINT DEFAULT 0,
  coins INT DEFAULT 0,
  hours_played INT DEFAULT 0,
  exp INT DEFAULT 0,
  respect INT DEFAULT 0,
  wanted INT DEFAULT 0,
  kills INT DEFAULT 0,
  deaths INT DEFAULT 0,
  last_ip VARCHAR(45) DEFAULT NULL,
  is_admin TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
